### ISSUE TITLE
width and height attributes can't have px values

### ISSUE THREAD

**Issue by KrijnHoetmer** [misspastelwitch/I-love-web#1]
Also for the rest of your images; the browser now ignores them. Don't put in units in your HTML.

https://github.com/misspastelwitch/I-love-web/blob/9d6913e578914ecb02f39d21df5570366ef72d14/index.html#L46C2-L46C3

**Comment by misspastelwitch** [comment]
Got rid of px values in HTML

**Comment by KrijnHoetmer** [comment]
Better!

Slightly unrelated, but next time try to mention the issue number in your commit message, so GitHub automatically attached your commit to this issue. If you use “fixes #1” in your commit message, it will also automatically close the issue once you push your code.
